CREATE TABLE STUDENT_MARKS (student_id int,name varchar(25),sub1 int,sub2 int,sub3 int,sub4 int,sub5 int,total float,per_marks float,grade varchar(25));
INSERT INTO STUDENT_MARKS VALUES (1,'A',0,0,0,0,0,0.00,0.00,'Undefined');
INSERT INTO STUDENT_MARKS VALUES (2,'B',0,0,0,0,0,0.00,0.00,'Undefined');
INSERT INTO STUDENT_MARKS VALUES (3,'B',0,0,0,0,0,0.00,0.00,'Undefined');
INSERT INTO STUDENT_MARKS VALUES (4,'D',0,0,0,0,0,0.00,0.00,'Undefined');


DELIMITER $$
CREATE TRIGGER `student_marks_BUPD` 
BEFORE UPDATE 
ON STUDENT_MARKS FOR EACH ROW
BEGIN 
SET NEW.TOTAL = NEW.SUB1 + NEW.SUB2 + NEW.SUB3 + NEW.SUB4 + NEW.SUB5; 
SET NEW.PER_MARKS = NEW.TOTAL/5;
IF NEW.PER_MARKS >=90 THEN
SET NEW.GRADE = 'EXCELLENT';
ELSEIF NEW.PER_MARKS>=75 AND NEW.PER_MARKS<90 THEN
SET NEW.GRADE = 'VERY GOOD';
ELSEIF NEW.PER_MARKS>=60 AND NEW.PER_MARKS<75 THEN
SET NEW.GRADE = 'GOOD';
ELSEIF NEW.PER_MARKS>=40 AND NEW.PER_MARKS<60 THEN
SET NEW.GRADE = 'AVERAGE';
ELSE SET NEW.GRADE = 'NOT PROMOTED';
END IF;
END;
$$
DELIMITER $$;

DELIMITER ;

UPDATE STUDENT_MARKS SET SUB1 = 54, SUB2 = 69, SUB3 = 89, SUB4 = 87, SUB5 = 59 WHERE STUDENT_ID = 1;

